### ISSUE TITLE
2.5.0 - Serebii den 129 is not showing available mons

### ISSUE THREAD

**Issue by MattBlower** [Admiral-Fish/RaidFinder#75] opened 2020-10-09 21:15 UTC
Title explains it all, loading up this den in any of the 3 locations doesnt show the list of available mons

![image](https://user-images.githubusercontent.com/37549563/95632160-f0f8ed00-0a7c-11eb-89bb-67f1d9325546.png)

**Comment by Admiral-Fish** [comment] 2020-10-09 23:06
Duplicate of #74

**Closed as completed by Admiral-Fish** 2020-10-09 23:06 UTC
