### ISSUE TITLE
Blank Spaces in Mac OS

### ISSUE THREAD

**Issue by DjaySuzi** [Admiral-Fish/RaidFinder#66] opened 2020-06-04 17:19 UTC
On the Mac OS version the first selection in the drop down menus are huge blank spaces. This becomes more of an issue when you download the raid data and you're unable to see/select the event den.

**Comment by Admiral-Fish** [comment] 2020-06-04 17:51
Probable duplicate of #23

**Closed as completed** 2020-06-12 04:00 UTC
