### ISSUE TITLE
Crash on Indeedee IV Calculation

### ISSUE THREAD

**Issue by papajefe** [Admiral-Fish/RaidFinder#86] opened 2021-02-05 18:50 UTC
This calculation crashes RaidFinder completely, no error message.

![image](https://user-images.githubusercontent.com/16225603/107076127-0840b080-67b9-11eb-959d-3c36edf6d33c.png)

**Expected results:**

![image](https://user-images.githubusercontent.com/16225603/107076217-1e4e7100-67b9-11eb-8ca4-f814bfb0824b.png)

**Comment by Admiral-Fish** [comment] 2021-02-05 18:52
Duplicate of #83

Temporary workaround: Add one more row then you actually are using

**Closed as completed by Admiral-Fish** 2021-02-05 18:52 UTC
