### ISSUE TITLE
Soothing Wetlands Rare (Purple Beam) No pokemon list

### ISSUE THREAD

**Issue by Garnet-Liu** [Admiral-Fish/RaidFinder#76] opened 2020-10-10 07:31 UTC
Soothing Wetlands Rare (Purple Beam) No pokemon list
![image](https://user-images.githubusercontent.com/34181559/95648936-8774ef00-0b0d-11eb-887e-cbbdcd5d8386.png)
version:2.5.0
Language:Chinese

**Comment by Admiral-Fish** [comment] 2020-10-10 08:51
Duplicate of #74

**Closed as completed by Admiral-Fish** 2020-10-10 08:51 UTC
